name: Release

permissions: read-all

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  COMPONENT_DIR: hsem

jobs:
  release_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        arch: [amd64,arm64]
        os: [linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download artifact from build workflow
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: pam_wrongpass_${{ matrix.arch }}_${{ matrix.arch }}.so
          path: .
          check_artifacts: true

      - name: Upload to the release
        uses: svenstaro/upload-release-action@2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./pam_wrongpass_${{ matrix.arch }}_${{ matrix.arch }}.so
          asset_name: pam_wrongpass_${{ matrix.arch }}_${{ matrix.arch }}.so
          tag: ${{ github.ref }}
          overwrite: true
